name: Simple Dev Build pipeline Unittest
on: 
  workflow_dispatch:
    push:
      branches:
        - main
jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.16.0'
    
    - name: Unittest
      run: |
        go test
